{% set name = "eeyore" %}
{% set version = "0.0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 27861b0768a2c8cc54e4313913670cd0787176f37248e8e9f4dfb4162973c84d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - cpuonly
    - kanga >=0.0.15
    - numpy >=1.19.2
    - python
    - pytorch
    - torchvision

test:
  imports:
    - eeyore
  requires:
    - pip

about:
  home: "https://github.com/papamarkou/eeyore"
  license: MIT
  license_file: LICENSE.txt
  summary: "MCMC methods for neural networks"

extra:
  recipe-maintainers:
    - papamarkou
