{% set name = "eeyore" %}
{% set version = "0.0.18" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 735ef6454c5167855dd17c781b4c9200ef7befd8c7fbfc0f370b67d84e8bc72b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - kanga >=0.0.17
    - numpy >=1.19.2
    - python >=3.6
    - pytorch-cpu >=1.9.0

test:
  imports:
    - eeyore

about:
  home: "https://github.com/papamarkou/eeyore"
  license: MIT
  license_file: LICENSE.txt
  summary: "MCMC methods for neural networks"

extra:
  recipe-maintainers:
    - papamarkou
